# automatically generated by the FlatBuffers compiler, do not modify

# namespace: req

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Request(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request
    def Code(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RequestStart(builder): builder.StartObject(1)
def Start(builder):
    return RequestStart(builder)
def RequestAddCode(builder, code): builder.PrependInt32Slot(0, code, 0)
def AddCode(builder, code):
    return RequestAddCode(builder, code)
def RequestEnd(builder): return builder.EndObject()
def End(builder):
    return RequestEnd(builder)