# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rep

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Reply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Reply()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReply(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Reply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Reply
    def Pose(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Reply
    def PoseAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Reply
    def PoseLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Reply
    def PoseIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ReplyStart(builder): builder.StartObject(1)
def Start(builder):
    return ReplyStart(builder)
def ReplyAddPose(builder, pose): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pose), 0)
def AddPose(builder, pose):
    return ReplyAddPose(builder, pose)
def ReplyStartPoseVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartPoseVector(builder, numElems):
    return ReplyStartPoseVector(builder, numElems)
def ReplyEnd(builder): return builder.EndObject()
def End(builder):
    return ReplyEnd(builder)